database:
  driver: postgres
  username: user_dKwZY5
  password: password_SxKEGb
  host: pgsql.pi.local
  port: 5432
  database: user_dKwZY5
  schema: public
redis:
  username: default
  password: redis_X632nF
  host: redis.pi.local
  port: 6379
  db: 0
jwt:
  secret: 'jwtsecret'
  duration: 10m
email:
  username:
  password: onughpsfvgyrdgbc
  host: smtp.qq.com
  port: 587
  subject: "This is my test mail"
